name: API YamDb workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api_yamdb/requirements-devel.txt

    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        cd api_yamdb
        python manage.py test
